# Below are the parameters used to alter a unity experiment with the name
# Hyperiid orientation experiment

# runs through multiple conditions
# where snells window and bioluminenscent appears above, to the right and below at two different intensities

# each experiment should take 58 minutes (with 2 repeats)

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 
# Space - start movement/reset looming of the stimulus
# IF manualControl==1,
# Move the mouse - Move the stimulus in polar coordinates around the center of the aquariums
# Scroll the mouse wheel - Make the stimulus larger or smaller
# 0 - recenter stimulus to the center of the front screen (polar coordinates: 0, 0).

# general
python_setup: 'n_conditions = 73; import random; from datetime import datetime; random.seed(datetime.now().timestamp())'
buildDir: ./builds/Loom/
frameDataIdCode: 'python: list(range(1, n_conditions + 1))'
animalCode: 1
# randomise the order of the conditions and repeat the experiment twice
execution_order: 'python: random.sample(list(range(0, n_conditions)), n_conditions) + random.sample(list(range(0, n_conditions)), n_conditions)'
cameraRotationX: [270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270, 90, 0, 270]
cameraRotationY: -90
cameraRotationZ: -90
experimentDuration: 40
recordFrameData: 1 
recordEachFrame: 1
recordingFrequency: 1 
manualControl: 0 
syncSquareColourR: 76
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 255
syncSquareTextColourR: 108
syncSquareTextColourG: 52
syncSquareTextColourB: 52
syncSquareTextColourA: 255
syncSquareStartedColourR: 179 
syncSquareStartedColourG: 51
syncSquareStartedColourB: 51
syncSquareStartedColourA: 255
syncSquareEndedColourR: 102 
syncSquareEndedColourG: 26
syncSquareEndedColourB: 26
syncSquareEndedColourA: 255
syncSquareDisplayNum: 3
syncSquareScalar: 2
displayStimulusCode: 1 
fictracFeedback: 0

use32BitColor: 1

# perspective
eyeHeight: 3.435 
distanceToMonitors: 7 
monitorDimensionsX: 12.176
monitorDimensionsY: 6.87
frontDisplayNum: 0 
rightDisplayNum: 3
backDisplayNum: 2
leftDisplayNum: 1
darkAdaptTime: 10000

# stimuli
# background
aboveHorizonColourR: [0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 20, 20, 20, 20, 20, 20, 20, 20, 20, 60, 60, 60, 60, 60, 60, 60, 60, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 20, 20, 20, 20, 20, 20, 20, 20, 20, 60, 60, 60, 60, 60, 60, 60, 60, 60]
aboveHorizonColourG: [0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 20, 20, 20, 20, 20, 20, 20, 20, 20, 60, 60, 60, 60, 60, 60, 60, 60, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 20, 20, 20, 20, 20, 20, 20, 20, 20, 60, 60, 60, 60, 60, 60, 60, 60, 60]
aboveHorizonColourB: [0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 20, 20, 20, 20, 20, 20, 20, 20, 20, 60, 60, 60, 60, 60, 60, 60, 60, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 20, 20, 20, 20, 20, 20, 20, 20, 20, 60, 60, 60, 60, 60, 60, 60, 60, 60]
aboveHorizonColourA: 255
belowHorizonColourR: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
belowHorizonColourG: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
belowHorizonColourB: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
belowHorizonColourA: 255
horizonHeight: [41.5, 87.0, 87.0, 87.0, 84.0, 84.0, 84.0, 41.5, 41.5, 41.5, 87.0, 87.0, 87.0, 84.0, 84.0, 84.0, 41.5, 41.5, 41.5, 87.0, 87.0, 87.0, 84.0, 84.0, 84.0, 41.5, 41.5, 41.5, 87.0, 87.0, 87.0, 84.0, 84.0, 84.0, 41.5, 41.5, 41.5, 87.0, 87.0, 87.0, 84.0, 84.0, 84.0, 41.5, 41.5, 41.5, 87.0, 87.0, 87.0, 84.0, 84.0, 84.0, 41.5, 41.5, 41.5, 87.0, 87.0, 87.0, 84.0, 84.0, 84.0, 41.5, 41.5, 41.5, 87.0, 87.0, 87.0, 84.0, 84.0, 84.0, 41.5, 41.5, 41.5]

# object - here we use it to hide the still object, by putting the animal inside
# this object for 20 seconds then hiding it to reveal the sill object. this has
# the same brightness as the background
autoStart: 1
stimulusType: 0
startScaleX: 1  
startScaleY: 1
startScaleZ: 1
endScaleX: 1
endScaleY: 1
endScaleZ: 1  
startElevation: 0
startAzimuth: 0  
endElevation: 0
endAzimuth: 0 
startDistance: 0
endDistance: 0
duration: 20 
numReps: 0 
delayToAppear: 0
delayToApproach: 0
hideAtEnd: 1
stimulusColourR: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
stimulusColourG: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
stimulusColourB: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
stimulusColourA: 255
