# A simple intensity calibration yaml file that uses
# the MovingRectangle stimulus to display simple changes in
# intensity

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 

# general
buildDir: ./builds/MovingRectangle
frameDataIdCode: 1 
animalCode: 1
execution_order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
experimentDuration: 99999 
recordFrameData: 1
recordEachFrame: 1 
recordingFrequency: 1
manualControl: 0 
mouseMoveSpeed: 2
flickerDuration: 0.1
syncSquareColourR: 1
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 1 
syncSquareDisplayNum: 0
displayStimulusCode: 1
darkAdaptTime: 0
fictracFeedback: 0

# perspective
eyeHeight: 3.435  
distanceToMonitors: 7 
monitorDimensionsX: 12.176
monitorDimensionsY: 6.87
frontDisplayNum: 0 
rightDisplayNum: 1
backDisplayNum: 2
leftDisplayNum: 3
cameraRotationX: 0
cameraRotationY: 0
cameraRotationZ: 0

# stimuli
# background
horizonHeight: -90
aboveHorizonColourR: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
aboveHorizonColourG: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
aboveHorizonColourB: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
aboveHorizonColourA: 1
belowHorizonColourR: 0
belowHorizonColourG: 0
belowHorizonColourB: 0
belowHorizonColourA: 0
# object
width: 0
height: 0
startPosX: 0 
startPosY: 0
endPosX: 0
endPosY: 0
numReps: 0
duration: 1
delayToApproach: 0
stimulusColourR: 0
stimulusColourG: 0
stimulusColourB: 0
stimulusColourA: 0
