# Below are the parameters used to alter a unity experiment with the name
# DualMoving

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 
# Space - start movement/reset the position of the stimulus
# IF manualControl==1,
# Move the mouse - Move the stimulus in polar coordinates around the center of the aquariums
# Scroll the mouse wheel - Make the stimulus larger or smaller
# 0 - recenter stimulus to the center of the front screen (polar coordinates: 0, 0).

# general
buildDir: ./builds/DualLoom
frameDataIdCode: [5, 3, 8, 7, 1, 4, 2, 1, 6, 2, 7, 5, 3, 6, 4, 8, 2, 3, 7, 8, 6, 4, 8, 1, 1, 2, 4, 6]
animalCode: [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14]
execution_order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
experimentDuration: 99999
recordFrameData: 1
recordEachFrame: 1
recordingFrequency: 1
manualControl: 0
mouseMoveSpeed: 2
flickerDuration: 0.1
syncSquareColourR: 1
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 1
syncSquareDisplayNum: 1
displayStimulusCode: 1
fictracFeedback: 0

# perspective
eyeHeight: [2.05, 2.05, 1.83, 1.83, 2.44, 2.44, 2.11, 2.11, 2.15, 2.15, 2.17, 2.17, 2.10, 2.10, 2.28, 2.28, 2.00, 2.00, 2.03, 2.03, 1.72, 1.72, 1.87, 1.87, 2.08, 2.08, 2.11, 2.11]
distanceToMonitors: 27
monitorDimensionsX: 52
monitorDimensionsY: 32
frontDisplayNum: 0
rightDisplayNum: 1
backDisplayNum: 2
leftDisplayNum: 3

rotationOffsetY1: [90, 0, 90, 0, 90, 0, 0, 90, 0, 90, 90, 0, 90, 0, 0, 90, 0, 90, 90, 0, 0, 90, 90, 0, 90, 0, 90, 0]
rotationOffsetY2: [90, 0, 90, 0, 90, 0, 0, 90, 0, 90, 90, 0, 90, 0, 0, 90, 0, 90, 90, 0, 0, 90, 90, 0, 90, 0, 90, 0]

# stimuli
# background
darkAdaptTime: 0
horizonHeight: 0

aboveHorizonColourR: 1
aboveHorizonColourG: 1
aboveHorizonColourB: 1
aboveHorizonColourA: 1
belowHorizonColourR: 0.3
belowHorizonColourG: 0.3
belowHorizonColourB: 0.3
belowHorizonColourA: 1

aboveHorizonColourRBack: 0
aboveHorizonColourGBack: 0
aboveHorizonColourBBack: 0
aboveHorizonColourABack: 1
belowHorizonColourRBack: 0.65
belowHorizonColourGBack: 0.65
belowHorizonColourBBack: 0.65
belowHorizonColourABack: 1

aboveHorizonColourRRight: 0
aboveHorizonColourGRight: 0
aboveHorizonColourBRight: 0
aboveHorizonColourARight: 1
belowHorizonColourRRight: 0.63
belowHorizonColourGRight: 0.63
belowHorizonColourBRight: 0.63
belowHorizonColourARight: 1

# object 1
stimulusType1: 0
startScaleX1: 1 
startScaleY1: 1
startScaleZ1: 1
endScaleX1: 1
endScaleY1: 1
endScaleZ1: 0
duration1: 5
startElevation1: 15
startAzimuth1: -15 
endElevation1: 15
endAzimuth1: -15
startDistance1: 50 
endDistance1: 5
numReps1: [0.5, 1] 
delayToApproach1: [5, 5] 
stimulusColourR1: 0.3 
stimulusColourG1: 0.3
stimulusColourB1: 0.3
stimulusColourA1: 1
drawOutline1: 0
outlineType1: 0
outlineWidth1: 1
outlineColourR1: 0
outlineColourG1: 0
outlineColourB1: 0
outlineColourA1: 1
originX1: [0, 0] 
originY1: [0, 0]
originZ1: [0, 0]

# object 2
stimulusType2: 0
startScaleX2: 1.5
startScaleY2: 1.5
startScaleZ2: 1.5
endScaleX2: 1.5
endScaleY2: 1.5
endScaleZ2: 1.5
duration2: 5
startElevation2: 15
startAzimuth2: 180
endElevation2: 15
endAzimuth2: 180 
startDistance2: 55 
endDistance2: 6  
numReps2: [0.5, 1] 
delayToApproach2: [5, 5]
stimulusColourR2: 0 
stimulusColourG2: 0
stimulusColourB2: 0
stimulusColourA2: 1
drawOutline2: 0
outlineType2: 0
outlineWidth2: 1
outlineColourR2: 0
outlineColourG2: 0
outlineColourB2: 0
outlineColourA2: 1
originX2: [0, 0]  
originY2: [0, 0] 
originZ2: [0, 0]
