# Below are the parameters used to alter a unity experiment with the name
# DualMoving

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 
# Space - start movement/reset the position of the stimulus
# IF manualControl==1,
# Move the mouse - Move the stimulus in polar coordinates around the center of the aquariums
# Scroll the mouse wheel - Make the stimulus larger or smaller
# 0 - recenter stimulus to the center of the front screen (polar coordinates: 0, 0).

# general
buildDir: ./builds/DualLoom
frameDataIdCode: [800001, 800002]
animalCode: [1, 2]
execution_order: [0, 1]
experimentDuration: 99999
recordFrameData: 1
recordEachFrame: 1
recordingFrequency: 1
manualControl: 0
mouseMoveSpeed: 2
flickerDuration: 0.1
syncSquareColourR: 1
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 1
syncSquareDisplayNum: 0
displayStimulusCode: 1
fictracFeedback: 0

# perspective
eyeHeight: 2.864
distanceToMonitors: 27
monitorDimensionsX: 52
monitorDimensionsY: 32
frontDisplayNum: 0
rightDisplayNum: 1
backDisplayNum: 2
leftDisplayNum: 3

# stimuli
# background
darkAdaptTime: 0
aboveHorizonColourR: 0.5
aboveHorizonColourG: 0.5
aboveHorizonColourB: 0.5
aboveHorizonColourA: 1
belowHorizonColourR: 0.3
belowHorizonColourG: 0.3
belowHorizonColourB: 0.3
belowHorizonColourA: 1
horizonHeight: 0 
# object 1
stimulusType1: 0
startScaleX1: 3 
startScaleY1: 3
startScaleZ1: 3
endScaleX1: 3
endScaleY1: 3
endScaleZ1: 3
duration1: 8
numReps1 : 0.5
startElevation1: 15
startAzimuth1: 0 
endElevation1: 15
endAzimuth1: 0 
startDistance1: 100 
endDistance1: 0 
delayToApproach1: 5
delayToAppear1: 0 
stimulusColourR1: 0
stimulusColourG1: 0
stimulusColourB1: 0
stimulusColourA1: 1
fixedAngularSize1: 0
fixElevation1: 1
minAngularAngle1: 15.5
maxAngularAngle1: 14.5
originX1: 0 
originY1: 0
originZ1: 0
# object 2
stimulusType2: 0
startScaleX2: 3
startScaleY2: 3
startScaleZ2: 3
endScaleX2: 3
endScaleY2: 3
endScaleZ2: 3
duration2: 4
numReps2 : 0.5
startElevation2: 15
startAzimuth2: 10 
endElevation2: 15
endAzimuth2: 10 
startDistance2: 50 
endDistance2: 0 
delayToApproach2: 9
delayToAppear2: 0
stimulusColourR2: 0 
stimulusColourG2: 0
stimulusColourB2: 0
stimulusColourA2: 1
fixedAngularSize2: 0
fixElevation2: 1
minAngularAngle2: 15.5
maxAngularAngle2: 14.5
originX2: 0  
originY2: 0 
originZ2: 0
mustIncludeEveryParameter: 0
