# Below are the parameters used to alter a unity experiment with the name
# DualMoving

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 
# Space - start movement/reset the position of the stimulus
# IF manualControl==1,
# Move the mouse - Move the stimulus in polar coordinates around the center of the aquariums
# Scroll the mouse wheel - Make the stimulus larger or smaller
# 0 - recenter stimulus to the center of the front screen (polar coordinates: 0, 0).

# general
buildDir: # ./builds/All
scene: 5
frameDataIdCode: [900001, 900002]
animalCode: [1, 2]
execution_order: [0, 1]
experimentDuration: [99999, 99999]
recordFrameData: 1
recordEachFrame: 1
recordingFrequency: 1
manualControl: 0
mouseMoveSpeed: 2
flickerDuration: 0.1
syncSquareColourR: 1
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 1
syncSquareDisplayNum: 0
displayStimulusCode: 1
fictracFeedback: 0

# perspective
eyeHeight: 2.864
distanceToMonitors: 27
monitorDimensionsX: 52
monitorDimensionsY: 32
frontDisplayNum: 0
rightDisplayNum: 1
backDisplayNum: 2
leftDisplayNum: 3

# stimuli
# background
darkAdaptTime: 0
aboveHorizonColourR: 0.5
aboveHorizonColourG: 0.5
aboveHorizonColourB: 0.5
aboveHorizonColourA: 1
belowHorizonColourR: 0.3
belowHorizonColourG: 0.3
belowHorizonColourB: 0.3
belowHorizonColourA: 1
horizonHeight: 0 
# object 1
stimulusType1: 4
startScaleX1: 1 
startScaleY1: 1
startScaleZ1: 1
endScaleX1: 1
endScaleY1: 1
endScaleZ1: 1
duration1: 5
startElevation1: 15
startAzimuth1: 10 
endElevation1: 15
endAzimuth1: 10 
startDistance1: 50 
endDistance1: 5
numReps1: [0.5, 1] 
delayToApproach1: [5, 5] 
stimulusColourR1: 0.3 
stimulusColourG1: 0.3
stimulusColourB1: 0.3
stimulusColourA1: 1
drawOutline1: 1
outlineType1: 1
outlineWidth1: 1000
outlineColourR1: 0
outlineColourG1: 0
outlineColourB1: 0
outlineColourA1: 1
fixedAngularSize1: 0
fixElevation1: 0
minAngularAngle1: -0.5
maxAngularAngle1: 0.5
originX1: [0, 0] 
originY1: [0, 0]
originZ1: [0, 0]
# object 2
stimulusType2: 1
startScaleX2: 1.5
startScaleY2: 1.5
startScaleZ2: 1.5
endScaleX2: 1.5
endScaleY2: 1.5
endScaleZ2: 1.5
duration2: 5
startElevation2: 15
startAzimuth2: 0 
endElevation2: 15
endAzimuth2: 0 
startDistance2: 55 
endDistance2: 6  
numReps2: [0.5, 1] 
delayToApproach2: [5, 5]
stimulusColourR2: 0 
stimulusColourG2: 0
stimulusColourB2: 0
stimulusColourA2: 1
drawOutline2: 0
outlineType2: 0
outlineWidth2: 1
outlineColourR2: 0
outlineColourG2: 0
outlineColourB2: 0
outlineColourA2: 1
fixedAngularSize2: 1
fixElevation2: 0
minAngularAngle2: -0.5
maxAngularAngle2: 0.5
originX2: [0, 0]  
originY2: [0, 0] 
originZ2: [0, 0]
# object 3
stimulusType3: 1
startScaleX3: 1.5
startScaleY3: 1.5
startScaleZ3: 1.5
endScaleX3: 1.5
endScaleY3: 1.5
endScaleZ3: 1.5
duration3: 5
startElevation3: 15
startAzimuth3: 0 
endElevation3: 15
endAzimuth3: 0 
startDistance3: 55 
endDistance3: 6  
numReps3: [0.5, 1] 
delayToApproach3: [5, 5]
stimulusColourR3: 0 
stimulusColourG3: 0
stimulusColourB3: 0
stimulusColourA3: 1
drawOutline3: 0
outlineType3: 0
outlineWidth3: 1
outlineColourR3: 0
outlineColourG3: 0
outlineColourB3: 0
outlineColourA3: 1
fixedAngularSize3: 1
fixElevation3: 0
minAngularAngle3: -0.5
maxAngularAngle3: 0.5
originX3: [0, 0]  
originY3: [0, 0] 
originZ3: [0, 0]
# object 4
stimulusType4: 1
startScaleX4: 1.5
startScaleY4: 1.5
startScaleZ4: 1.5
endScaleX4: 1.5
endScaleY4: 1.5
endScaleZ4: 1.5
duration4: 5
startElevation4: 15
startAzimuth4: 0 
endElevation4: 15
endAzimuth4: 0 
startDistance4: 55 
endDistance4: 6  
numReps4: [0.5, 1] 
delayToApproach4: [5, 5]
stimulusColourR4: 0 
stimulusColourG4: 0
stimulusColourB4: 0
stimulusColourA4: 1
drawOutline4: 0
outlineType4: 0
outlineWidth4: 1
outlineColourR4: 0
outlineColourG4: 0
outlineColourB4: 0
outlineColourA4: 1
fixedAngularSize4: 1
fixElevation4: 0
minAngularAngle4: -0.5
maxAngularAngle4: 0.5
originX4: [0, 0]  
originY4: [0, 0] 
originZ4: [0, 0]
