# Below are the parameters used to alter a unity experiment with the name
# Optomotor

# each experiment should take around 18 minutes

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 

# general
buildDir: ./builds/Optomotor/
frameDataIdCode: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48] 
animalCode: 22
execution_order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]
experimentDuration: 180
reverseAfterSeconds: 30

recordFrameData: 1
recordEachFrame: 1
recordingFrequency: 1
manualControl: 0 
mouseMoveSpeed: 2 
flickerDuration: 0.1
syncSquareColourR: 0.3
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 1 
syncSquareTextColourR: 0.7
syncSquareTextColourG: 0.4
syncSquareTextColourB: 0.4
syncSquareTextColourA: 1
syncSquareDisplayNum: 3
syncSquareScalar: 2
displayStimulusCode: 1

# perspective
eyeHeight: 3.435 
distanceToMonitors: 7 
monitorDimensionsX: 12.176
monitorDimensionsY: 6.87
frontDisplayNum: 0 
rightDisplayNum: 1 
backDisplayNum: 2
leftDisplayNum: 3
darkAdaptTime: 10000

# stimuli
# change to 4 8 16
# run a experiment with 8 and 16 at different speeds first up
# we just want to get something
density: [4, 4, 4, 4, 4, 4, 8, 8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 32, 32, 32, 32, 32, 32, 4, 4, 4, 4, 4, 4, 8, 8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 32, 32, 32, 32, 32, 32]
offset: 0 
angle: 0
speed: [0.125, 0.25, 0.5, 1, 2, 4, 0.125, 0.25, 0.5, 1, 2, 4, 0.125, 0.25, 0.5, 1, 2, 4, 0.125, 0.25, 0.5, 1, 2, 4, 0.125, 0.25, 0.5, 1, 2, 4, 0.125, 0.25, 0.5, 1, 2, 4, 0.125, 0.25, 0.5, 1, 2, 4, 0.125, 0.25, 0.5, 1, 2, 4] 
square: 1
minimumVal: 0 
maximumVal: 0.005
