# Below are the parameters used to alter a unity experiment with the name
# Optomotor

# each experiment should take around 36 minutes

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 

# general
python_setup: >
  import random;
  from datetime import datetime;
  from itertools import product;
  random.seed(datetime.now().timestamp());
  n_conditions = 18;
  spatial_freqs = [0.01, 0.1, 1];
  temporal_freqs = [0.1, 1, 10];
  frequency_per_360 = [round(s * 360) for s, t in product(spatial_freqs, temporal_freqs)] * 2;
  p = product(spatial_freqs, temporal_freqs);
  velocities = [t / s for s, t in product(spatial_freqs, temporal_freqs)] * 2;
buildDir: ./builds/Optomotor/
frameDataIdCode: 'python: list(range(1, n_conditions + 1))'
animalCode: 50
execution_order: 'python: random.sample(list(range(0, n_conditions)), n_conditions) + random.sample(list(range(0, n_conditions)), n_conditions)'
experimentDuration: 180
reverseAfterSeconds: 30

recordFrameData: 1
recordEachFrame: 1
recordingFrequency: 1
manualControl: 0 
mouseMoveSpeed: 2 
flickerDuration: 0.1
syncSquareColourR: 77
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 255 
syncSquareTextColourR: 179
syncSquareTextColourG: 102
syncSquareTextColourB: 102
syncSquareTextColourA: 255
syncSquareDisplayNum: 2
syncSquareScalar: 2
syncSquarePosY: 480
displayStimulusCode: 1
use32BitColor: 1

# perspective
eyeHeight: 3.435 
distanceToMonitors: 7 
monitorDimensionsX: 12.176
monitorDimensionsY: 6.87
frontDisplayNum: 0 
rightDisplayNum: 1 
backDisplayNum: 2
leftDisplayNum: 3
darkAdaptTime: 10000

# stimuli
density: 'python: frequency_per_360' # cycles per degree converted to frequency per 360 degrees
offset: 'python: random.choices([0, 90, 180, 270], k=n_conditions)'
speed: 'python: velocities' # in degrees per second
square: 1
minimumVal: 0 
maximumVal: 20
onlyShowOneHalfCycle: 'python: [0] * 9 + [1] * 9'
