# Below are the parameters used to alter a unity experiment with the name
# Hyperiid orientation experiment

# runs through multiple conditions
# where snells window appears above, to the right and below at two different intensities

# each experiment should take 23 minutes

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 
# Space - start movement/reset looming of the stimulus
# IF manualControl==1,
# Move the mouse - Move the stimulus in polar coordinates around the center of the aquariums
# Scroll the mouse wheel - Make the stimulus larger or smaller
# 0 - recenter stimulus to the center of the front screen (polar coordinates: 0, 0).

# general
buildDir: ./builds/Loom/
frameDataIdCode: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 50, 60, 70, 72, 80, 90, 100]
animalCode: 1
execution_order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]

# calibrated bottom screen

cameraRotationX: 270
cameraRotationY: -90
cameraRotationZ: -90
experimentDuration: 9999
recordFrameData: 1 
recordEachFrame: 1
recordingFrequency: 1 
manualControl: 0 
syncSquareColourR: 76
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 255
syncSquareTextColourR: 178
syncSquareTextColourG: 102
syncSquareTextColourB: 102
syncSquareTextColourA: 255
syncSquareDisplayNum: 0
syncSquareScalar: 2
displayStimulusCode: 1 
fictracFeedback: 0

use32BitColor: 1

# perspective
eyeHeight: 3.435 
distanceToMonitors: 7 
monitorDimensionsX: 12.176
monitorDimensionsY: 6.87
frontDisplayNum: 0 
rightDisplayNum: 1
backDisplayNum: 2
leftDisplayNum: 3
darkAdaptTime: 10000

# stimuli
# background
aboveHorizonColourR: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 50, 60, 70, 72, 80, 90, 100]
aboveHorizonColourG: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 50, 60, 70, 72, 80, 90, 100]
aboveHorizonColourB: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 50, 60, 70, 72, 80, 90, 100]
aboveHorizonColourA: 255
belowHorizonColourR: 0
belowHorizonColourG: 0
belowHorizonColourB: 0
belowHorizonColourA: 255
horizonHeight: 41.5
# object
stimulusType: 0
startScaleX: 0  
startScaleY: 0
startScaleZ: 0
endScaleX: 0
endScaleY: 0
endScaleZ: 0  
startElevation: 15 
startAzimuth: 0  
endElevation: 15
endAzimuth: 0 
startDistance: 15
endDistance: 15 
duration: 8 
numReps: 0.5 
delayToApproach: 1005 
stimulusColourR: 0
stimulusColourG: 0
stimulusColourB: 0
stimulusColourA: 255