# Below are the parameters used to alter a unity experiment with the name
# Loom

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 
# Space - start movement/reset looming of the stimulus
# IF manualControl==1,
# Move the mouse - Move the stimulus in polar coordinates around the center of the aquariums
# Scroll the mouse wheel - Make the stimulus larger or smaller
# 0 - recenter stimulus to the center of the front screen (polar coordinates: 0, 0).

# general
buildDir: ./builds/Loom/
frameDataIdCode: [1, 2]
animalCode: [1, 2] 
execution_order: [0, 1]
experimentDuration: 99999 
recordFrameData: 1 
recordEachFrame: 1
recordingFrequency: 1 
manualControl: 0 
mouseMoveSpeed: 2 
flickerDuration: 0.1
syncSquareColourR: 1
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 1
syncSquareDisplayNum: 0 
displayStimulusCode: 1 
fictracFeedback: 0

# perspective
eyeHeight: 2.864 
distanceToMonitors: 27 
monitorDimensionsX: 52 
monitorDimensionsY: 32 
frontDisplayNum: 0 
rightDisplayNum: 1 
backDisplayNum: 2
leftDisplayNum: 3
darkAdaptTime: 0

# stimuli
# background
aboveHorizonColourR: 0.5
aboveHorizonColourG: 0.5
aboveHorizonColourB: 0.5
aboveHorizonColourA: 1
belowHorizonColourR: 0.3
belowHorizonColourG: 0.3
belowHorizonColourB: 0.3
belowHorizonColourA: 1
horizonHeight: 0  

# object
stimulusType: 0
startScaleX: 3
startScaleY: 3
startScaleZ: 3
endScaleX: 3
endScaleY: 3
endScaleZ: 3  
startPolarPositionX: -15
startPolarPositionY: 0
endPolarPositionX: -15 ## use equation to calculate 
endPolarPositionY: 0 ## use equation to calculate 
targetLocationOffsetX: 0
targetLocationOffsetY: 0
targetLocationOffsetZ: 0 
startOffset: 500
endOffset: 1.5
duration: 5
delayToApproach: 5 
stimulusColourR: 0
stimulusColourG: 0
stimulusColourB: 0
stimulusColourA: 1
drawOutline: 0
outlineWidth: 1
outlineColourR: 0
outlineColourG: 0
outlineColourB: 0
outlineColourA: 1
fixedAngularSize: 0
fixXAxis: 0 
minAngularAngle: -15.5
maxAngularAngle: -14.5
