# general
buildDir: ./builds/Loom/
scene: 0
frameDataIdCode: [1, 3]
animalCode: [6] 
execution_order: [0, 1]
experimentDuration: 99999 
recordFrameData: 1 
recordEachFrame: 1
recordingFrequency: 1 
manualControl: 0 
mouseMoveSpeed: 2 
flickerDuration: 0.1
syncSquareColourR: 1
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 1
syncSquareDisplayNum: 1
displayStimulusCode: 1 
fictracFeedback: 0
syncSquareTextColourR: 1
syncSquareTextColourB: 1
syncSquareTextColourG: 1

# perspective
eyeHeight: 2.00
distanceToMonitors: 27 
monitorDimensionsX: 52 # 52
monitorDimensionsY: 32 # 32
frontDisplayNum: 0 
rightDisplayNum: 1 
backDisplayNum: 2
leftDisplayNum: 3
darkAdaptTime: 0

# stimuli
# background
aboveHorizonColourR: 0.5
aboveHorizonColourG: 0.5
aboveHorizonColourB: 0.5
aboveHorizonColourA: 1
belowHorizonColourR: 0.3
belowHorizonColourG: 0.3
belowHorizonColourB: 0.3
belowHorizonColourA: 1
horizonHeight: 0  

# object
stimulusType: 1
startScaleX: [3, 400]
startScaleY: 3
startScaleZ: 3
endScaleX: [3, 400]
endScaleY: 3
endScaleZ: 3
startElevation: 15 
startAzimuth: [180, 270]
endElevation: 15
endAzimuth: [180, 270]
startDistance: 500 
endDistance: 1.5
duration: 24.925 # 24.925 (to get 200 mm/s with 1.5 cm end dist)
originX: 0 
originY: 0 
originZ: 0 
delayToApproach: 5 
stimulusColourR: 0
stimulusColourG: 0
stimulusColourB: 0
stimulusColourA: 1
drawOutline: 0
outlineWidth: 1
outlineColourR: 0
outlineColourG: 0
outlineColourB: 0
outlineColourA: 1
fixedAngularSize: [0, 1]
fixElevation: 0 
minAngularAngle: -3.185
maxAngularAngle: 3.185

