# general
buildDir: ./builds/DualLoom
frameDataIdCode: [13, 3]
animalCode: [1, 1] 
execution_order: [0, 1]
experimentDuration: 99999 
recordFrameData: 1 
recordEachFrame: 1
recordingFrequency: 1 
manualControl: 0 
mouseMoveSpeed: 2 
flickerDuration: 0.1
syncSquareColourR: 1
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 1
syncSquareDisplayNum: 1 
displayStimulusCode: 1 
fictracFeedback: 0

# perspective
eyeHeight: 1.918
distanceToMonitors: 27 
monitorDimensionsX: 52 
monitorDimensionsY: 32 
frontDisplayNum: 0 
rightDisplayNum: 1 
backDisplayNum: 2
leftDisplayNum: 3
darkAdaptTime: 0

# stimuli
# background
aboveHorizonColourR: 0.5
aboveHorizonColourG: 0.5
aboveHorizonColourB: 0.5
aboveHorizonColourA: 1
belowHorizonColourR: 0.3
belowHorizonColourG: 0.3
belowHorizonColourB: 0.3
belowHorizonColourA: 1
horizonHeight: 0  

# object 1 direct looms 
stimulusType1: [0, 1]
startScaleX1: [3, 50]
startScaleY1: [3, 2]
startScaleZ1: [3, 2]
endScaleX1: [3, 50]
endScaleY1: [3, 2]
endScaleZ1: [3, 2]
startElevation1: 15 
startAzimuth1: 0  
endElevation1: 15
endAzimuth1: 0 
startDistance1: 500 
endDistance1: 1.5
duration1: 24.925 
originX1: 0 
originY1: 0 
originZ1: 0 
rotationOffsetY1: [180, 90]
delayToApproach1: 5 
stimulusColourR1: [0, 0.5]
stimulusColourG1: [0, 0.5]
stimulusColourB1: [0, 0.5]
stimulusColourA1: 1
drawOutline1: 0
outlineWidth1: 1
outlineColourR1: 0
outlineColourG1: 0
outlineColourB1: 0
outlineColourA1: 1
fixedAngularSize1: 0
fixElevation1: 0 
minAngularAngle1: -15.5
maxAngularAngle1: -14.5
numReps1: 0.5
hideAtEnd1: 1
opaqueObject1: [0, 1]

# object 2 near miss looms 
stimulusType2: [0, 1]
startScaleX2: [3, 2]
startScaleY2: [3, 2]
startScaleZ2: [3, 2]
endScaleX2: [3, 2]
endScaleY2: [3, 2]
endScaleZ2: [3, 2]
startElevation2: 15 
startAzimuth2: 0  
endElevation2: [41.06, 15]
endAzimuth2: [82.3, 0]
startDistance2: 500 
endDistance2: [2.12, 1.5]
duration2: 24.925 
originX2: 0 
originY2: 0 
originZ2: 0 
rotationOffsetY2: [0, 270]
delayToApproach2: 5 
stimulusColourR2: 0
stimulusColourG2: 0
stimulusColourB2: 0
stimulusColourA2: 1
outlineType2: 1
drawOutline2: [0, 1]
outlineWidth2: 33.33
outlineColourR2: [0, 0.5]
outlineColourG2: [0, 0.5]
outlineColourB2: [0, 0.5]
outlineColourA2: 1
fixedAngularSize2: 0
fixElevation2: 0 
minAngularAngle2: -15.5
maxAngularAngle2: -14.5
numReps2: 0.5
hideAtEnd2: 1
opaqueObject2: 0
