# Below are the parameters used to alter a unity experiment with the name
# MovingRectangle

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 

# general
buildDir: ./builds/MovingRectangle
frameDataIdCode: [100001, 100002] 
animalCode: [1, 2] 
execution_order: [0, 1]
experimentDuration: 99999 
recordFrameData: 1
recordEachFrame: 1 
recordingFrequency: 1
manualControl: 0 
mouseMoveSpeed: 2
flickerDuration: 0.1
syncSquareColourR: 1
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 1 
syncSquareDisplayNum: 0
displayStimulusCode: 1
darkAdaptTime: 0
fictracFeedback: 0

# perspective
eyeHeight: 3.435  
distanceToMonitors: 7 
monitorDimensionsX: 12.176
monitorDimensionsY: 6.87
frontDisplayNum: 0 
rightDisplayNum: 1
backDisplayNum: 2
leftDisplayNum: 3
cameraRotationX: 0
cameraRotationY: 0
cameraRotationZ: 0

# stimuli
# background
horizonHeight: 0
aboveHorizonColourR: 0.4
aboveHorizonColourG: 0.4
aboveHorizonColourB: 0.4
aboveHorizonColourA: 1
belowHorizonColourR: 0.2
belowHorizonColourG: 0.2
belowHorizonColourB: 0.2
belowHorizonColourA: 1
# object
width: 300
height: 300
startPosX: [0, 0] 
startPosY: [0, 500]
endPosX: [800, 500]
endPosY: [0, 500]
numReps: [0.5, 1]
duration: 1
delayToApproach: 5
stimulusColourR: 1
stimulusColourG: 1
stimulusColourB: 1
stimulusColourA: 1
