#-----------------------------------------------------------------------------------#
#### HYPERIID BEHAVIOR OBJECTS                                                   ####
#-----------------------------------------------------------------------------------#
# Code by Jake Manger
# adapted by Vanessa Stenvers for MSM126
# 9 color intensities (one dark, 7 bright)  
  # intensities = 0, 7, 14, 21, 28, 35, 49, 63, 100 - randomized with MATLAB
# 2 speeds (5 and 10 seconds) - randomized with MATLAB
# 1 Background color = 3 (dark)
#-----------------------------------------------------------------------------------#
# Tank nr: 1 -----------------------------------------------------------------------#

#### RANDOMIZATION MATLAB ####
# rng seed = 163653
execution_order: [0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53]
cameraRotationX: [90,0,90,0,90,180,90,180,180,0,0,180,180,180,90,180,90,0,0,180,90,0,90,90,0,0,0,0,180,0,180,0,90,90,90,0,180,180,90,0,180,180,90,0,180,0,0,180,90,90,90,180,180,90]
stimulusColourR: [100,49,7,100,21,7,28,63,100,63,0,14,21,35,7,63,49,49,28,7,35,100,0,63,35,14,7,0,21,35,28,63,35,21,14,14,35,49,28,28,0,28,0,7,14,21,21,100,14,100,63,49,0,49]
stimulusColourG: [100,49,7,100,21,7,28,63,100,63,0,14,21,35,7,63,49,49,28,7,35,100,0,63,35,14,7,0,21,35,28,63,35,21,14,14,35,49,28,28,0,28,0,7,14,21,21,100,14,100,63,49,0,49]
stimulusColourB: [100,49,7,100,21,7,28,63,100,63,0,14,21,35,7,63,49,49,28,7,35,100,0,63,35,14,7,0,21,35,28,63,35,21,14,14,35,49,28,28,0,28,0,7,14,21,21,100,14,100,63,49,0,49]
stimulusColourA: [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]
duration: [10,10,10,5,5,5,5,5,10,5,5,10,10,10,5,10,5,5,10,10,10,10,10,10,5,10,5,10,5,10,5,10,5,10,10,5,5,5,10,5,10,10,5,10,5,5,10,5,5,5,5,10,5,10]

#### PARAMETERS TO SET ####
darkAdaptTime: 0 # Dark adaptation in seconds --> 100 = ~2 min, 1000 = ~ 17 minutes
experimentDuration: 120 # Duration single stimuli in seconds = 2 min

#### SCREEN PERSPECTIVES ####
eyeHeight: 7.1 # half of monitorDimensionsY
distanceToMonitors: 12.4 # The distance from the center of the eye to all monitors (cm).
monitorDimensionsX: 22.6
monitorDimensionsY: 14.2
backDisplayNum: 1  #= display nr 2 = bottom    
leftDisplayNum: 2 #= display nr 3
frontDisplayNum: 3 #= display nr 4 = top
rightDisplayNum: 4 #= display nr 5 
#### Display nr 0 is local display

# GENERAL
# Can python setup to randomize stimulus conditions, but not needed here since done with MATLAB (copy+pasted above)
  ## set n_conditions based on stimulus conditions used
# python_setup: 'n_conditions = 9; import random; from datetime import datetime; random.seed(datetime.now().timestamp())'
buildDir: ./builds/All
scene: 0
frameDataIdCode: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53]
animalCode: 1
cameraRotationY: -90
cameraRotationZ: -90 
recordFrameData: 1 
recordEachFrame: 1
recordingFrequency: 1 
manualControl: 0 

# Set parameters of sync square
syncSquareColourR: 76
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 255
syncSquareTextColourR: 108
syncSquareTextColourG: 52
syncSquareTextColourB: 52
syncSquareTextColourA: 255
syncSquareStartedColourR: 179 
syncSquareStartedColourG: 51
syncSquareStartedColourB: 51
syncSquareStartedColourA: 255
syncSquareEndedColourR: 102 
syncSquareEndedColourG: 26
syncSquareEndedColourB: 26
syncSquareEndedColourA: 255
syncSquareDisplayNum: 1 #set what display shows sync square
syncSquareScalar: 2
displayStimulusCode: 1 
fictracFeedback: 0
#syncSquarePosX: 11.3 # half of x dimension monitor
#syncSquarePosY: 1 #towards camera

use32BitColor: 1

#### STIMULI ####
## background
aboveHorizonColourR: [3] 
aboveHorizonColourG: [3]
aboveHorizonColourB: [3]
aboveHorizonColourA: 255
belowHorizonColourR: [3]
belowHorizonColourG: [3]
belowHorizonColourB: [3]
belowHorizonColourA: 255

horizonHeight: [0] ## The height of the horizon in degrees (0 is exactly horizontal relative to the eye position).
# NB For HorizonColourRGBA-Back/Left/Front/Right to work, set horizonHeight-Back/Left/Front/Right
horizonHeightFront: [0] ## The height of the horizon in degrees (0 is exactly horizontal relative to the eye position).
horizonHeightLeft: [0] ## The height of the horizon in degrees (0 is exactly horizontal relative to the eye position).
horizonHeightBack: [0] ## The height of the horizon in degrees (0 is exactly horizontal relative to the eye position).
horizonHeightRight: [0] ## The height of the horizon in degrees (0 is exactly horizontal relative to the eye position).


# OBJECT - here you can use a still object to hide the stimuli object, by putting the animal inside
  # use 'duration' to set the duration of the still object. The still object has the same brightness as the background.
autoStart: 1
stimulusType: 0 # 0 = sphere, 1 =square, 2= sphere with grating
  ## The scale of the stimulus at the start of the stimulus
startScaleX: 3 #cm
startScaleY: 3 #cm
startScaleZ: 3 #cm
  ## The scale of the stimulus at the end
endScaleX: 3 #cm
endScaleY: 3 #cm
endScaleZ: 3 #cm
  ## Stimulus polar position at start of stimulus
   # X (elevation) and Y (azimuth) are rotational axes, so X is up and down, Y is left and right. 
   # X is the equivalent of negative elevation, Y is the equivalent of azimuth.
startElevation: -40 # Default = 0 ## Can be -90 to 90
startAzimuth: 90  # Default = 0 ## Can be -180 to 180
  ## Stimulus polar position at end of stimulus
endElevation: 40
endAzimuth: 90
  ## The offset of the stimulus from the eye position in cm at the start of the loom
startDistance: 12.4 # Can be zero to 'infinity'
  ## The offset of the stimulus from the eye position in cm at the end of the loom
endDistance: 12.4 
numReps: 1 # The number of times to repeat the stimulus movement (0.5 is start-finish, 1 is start-finish-start).
delayToAppear: 0 # The delay in seconds before the stimulus object appears.
delayToApproach: 10 # The delay in seconds before the stimulus starts
hideAtEnd: 1 # 0= false, 1= true
directPath: 0 # 0= false, 1= true


#### DOCUMENTATION ####

# Below are the parameters used to alter a unity experiment where still objects,
  # snells window and bioluminenscent objects or silhouttes appears above, 
  # to the right and below at multiple light intensities.

# Each experiment should take 73 * 40 seconds = 49 minutes (with 2 repeats).
# The first and last displayed screens are completely black (for dark adaptation).
# Once you are ready to start the experiment, press escape and make sure to hide the mouse
  # in the corner of the screen (it can sometimes appear when you press escape).
# You will see the sync square in the bottom of one of the screens indicating what condition
  # is being displayed and the animal id you set in this file.
# For the first 20 seconds, a new background will be set, with a ball covering the animals
  # view in all directions. Then, the ball will dissapear revealing a snells window, bioluminenscent object
  # or silhoutte. After another 20 seconds, the next condition will be displayed.
# The order of experiment are randomised with the python part of the configuration file for you.
# Just enter the stimulus conditions you wish to use and make sure to update the n_conditions parameter in
  # python_setup.

# logs will be saved in the trial_logs/ directory with the parameters used and positional information
# each frame from unity.

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 
# Space - start movement/reset looming of the stimulus
# IF manualControl==1,
# Move the mouse - Move the stimulus in polar coordinates around the center of the aquariums
# Scroll the mouse wheel - Make the stimulus larger or smaller
# 0 - recenter stimulus to the center of the front screen (polar coordinates: 0, 0).
