# Below are the parameters used to alter a unity experiment where still objects,
  # snells window and bioluminenscent objects or silhouttes appear above, 
  # to the right and below at multiple light intensities.

# Each experiment should take 73 * 40 seconds = 49 minutes (with 2 repeats).
# The first and last displayed screens are completely black (for dark adaptation).
# Once you are ready to start the experiment, press escape and make sure to hide the mouse
  # in the corner of the screen (it can sometimes appear when you press escape).
# You will see the sync square in the bottom of one of the screens indicating what condition
  # is being displayed and the animal id you set in this file.
# For the first 20 seconds, a new background will be set, with a ball covering the animals
  # view in all directions. Then, the ball will dissapear revealing a snells window, bioluminenscent object
  # or silhoutte. After another 20 seconds, the next condition will be displayed.
# The order of experiment are randomised with the python part of the configuration file for you.
# Just enter the stimulus conditions you wish to use and make sure to update the n_conditions parameter in
  # python_setup.

# logs will be saved in the trial_logs/ directory with the parameters used and positional information
# each frame from unity.

# Controls for the experiment
# escape - stall Unity, end the experiment and give control to python.
# F - flicker the stimulus and the sync square to sync unity with the camera
# IF displayStimulusCode == True, then F just fades displayStimulusCode from off to on or on to off
# tab - Unlock/lock the cursor from Unity allowing you to see or not see your mouse 
# Space - start movement/reset looming of the stimulus
# IF manualControl==1,
# Move the mouse - Move the stimulus in polar coordinates around the center of the aquariums
# Scroll the mouse wheel - Make the stimulus larger or smaller
# 0 - recenter stimulus to the center of the front screen (polar coordinates: 0, 0).

#### GENERAL ####
  ## Call python setup to randomize stimulus conditions
  ## set n_conditions based on stimulus conditions used
python_setup: 'n_conditions = 4; import random; from datetime import datetime; random.seed(datetime.now().timestamp())'
buildDir: ./builds/All
scene: 0
frameDataIdCode: 'python: list(range(1, n_conditions + 1))'
animalCode: 1

# Randomise the order of the conditions and repeat the experiment twice
execution_order: 'python: random.sample(list(range(0, n_conditions)), n_conditions) + random.sample(list(range(0, n_conditions)), n_conditions)' 
cameraRotationX: [0, 90, 270, 0] 
cameraRotationY: -90
cameraRotationZ: -90 
experimentDuration: 120 # seconds
recordFrameData: 1 
recordEachFrame: 1
recordingFrequency: 1 
manualControl: 0 

syncSquareColourR: 76
syncSquareColourG: 0
syncSquareColourB: 0
syncSquareColourA: 255
 
syncSquareTextColourR: 108
syncSquareTextColourG: 52
syncSquareTextColourB: 52
syncSquareTextColourA: 255

syncSquareStartedColourR: 179 
syncSquareStartedColourG: 51
syncSquareStartedColourB: 51
syncSquareStartedColourA: 255

syncSquareEndedColourR: 102 
syncSquareEndedColourG: 26
syncSquareEndedColourB: 26
syncSquareEndedColourA: 255

syncSquareDisplayNum: 3 #set on what display the Sync square is shown
syncSquareScalar: 2
displayStimulusCode: 1 #0= false,1=true
fictracFeedback: 0

use32BitColor: 1

#### PERSPECTIVE ####
eyeHeight: 7.1 # half of monitorDimensionsY
distanceToMonitors: 12.4 # The distance from the center of the eye to all monitors (cm).
monitorDimensionsX: 22.6
monitorDimensionsY: 14.2
backDisplayNum: 1  #= display nr 2 = top    
leftDisplayNum: 2 #= display nr 3
frontDisplayNum: 3 #= display nr 4 = bottom
rightDisplayNum: 4 #= display nr 5
#### Display nr 0 is local display
darkAdaptTime: 0 # seconds --> 100 = ~2 min, 1000 = ~ 17 minutes

#### STIMULI ####
## background
aboveHorizonColourR: [255] 
aboveHorizonColourG: [0]
aboveHorizonColourB: [0]
aboveHorizonColourA: 255
belowHorizonColourR: [0]
belowHorizonColourG: [255]
belowHorizonColourB: [0]
belowHorizonColourA: 255

# Set colours for each display (back, left, front and right), overriding default aboveHorizonColour commands above
  # Above horizon
aboveHorizonColourRBack: [0, 6, 12] #top
aboveHorizonColourGBack: [0, 6, 12] 
aboveHorizonColourBBack: [0, 6, 12]
aboveHorizonColourABack: 1

aboveHorizonColourRLeft: [6, 12, 6]
aboveHorizonColourGLeft: [6, 12, 6]
aboveHorizonColourBLeft: [6, 12, 6]
aboveHorizonColourALeft: 255

aboveHorizonColourRFront: [12, 6, 0]
aboveHorizonColourGFront: [12, 6, 0]
aboveHorizonColourBFront: [12, 6, 0]
aboveHorizonColourAFront: 255

aboveHorizonColourRRight: [6, 0, 6]
aboveHorizonColourGRight: [6, 0, 6]
aboveHorizonColourBRight: [6, 0, 6]
aboveHorizonColourARight: 255

# Below horizon
belowHorizonColourRBack: [0, 6, 12] #top
belowHorizonColourGBack: [0, 6, 12]
belowHorizonColourBBack: [0, 6, 12]
belowHorizonColourABack: 255

belowHorizonColourRLeft: [6, 12, 6]
belowHorizonColourGLeft: [6, 12, 6]
belowHorizonColourBLeft: [6, 12, 6]
belowHorizonColourALeft: 255

belowHorizonColourRFront: [12, 6, 0]
belowHorizonColourGFront: [12, 6, 0]
belowHorizonColourBFront: [12, 6, 0]
belowHorizonColourAFront: 255

belowHorizonColourRRight: [6, 0, 6]
belowHorizonColourGRight: [6, 0, 6]
belowHorizonColourBRight: [6, 0, 6]
belowHorizonColourARight: 255

horizonHeight: [0] ## The height of the horizon in degrees (0 is exactly horizontal relative to the eye position).

# NB For HorizonColourRGBA-Back/Left/Front/Right to work, set horizonHeight-Back/Left/Front/Right
horizonHeightFront: [0] ## The height of the horizon in degrees (0 is exactly horizontal relative to the eye position).
horizonHeightLeft: [0] ## The height of the horizon in degrees (0 is exactly horizontal relative to the eye position).
horizonHeightBack: [0] ## The height of the horizon in degrees (0 is exactly horizontal relative to the eye position).
horizonHeightRight: [0] ## The height of the horizon in degrees (0 is exactly horizontal relative to the eye position).
